env:
  node: true
  es6: true
  mocha: true

rules:
  no-console: 0
  no-var: 2
  indent: ["error", "tab", { "SwitchCase": 1}]
  eqeqeq: ["error", "always"]

extends: eslint:recommended

plugins: [ejs]